runtime: go113

handlers:

- url: /(.*\.(gif|png|jpg|ico|txt))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg|ico|txt)$
  secure: always

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

- url: /static
  static_dir: frontend-light-bootstrap-dashboard-react/build/static/

- url: /uploadLive
  script: auto

- url: /downloadLive
  script: auto

- url: /createClaimsEvent
  script: auto
